/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CONTENEDORMDI;

import P.TRANSACCIONALES.AsignacionEstudiantes;
import Mantenimiento.Facultades;
import Mantenimiento.Cursos;
import Mantenimiento.Carreras;
import Mantenimiento.MantenimientoAlumnos;
import Mantenimiento.MantenimientoMaestros;
import Mantenimiento.Secciones;



/**
 *
 * @author Jacky
 */
public class ContenedorMDI extends javax.swing.JFrame {
private AsignacionEstudiantes ventana3;
    /**
     * Creates new form ContenedorMDI
     */
    public ContenedorMDI() {
        
        initComponents();
        jDesktopPane1.setBorder(new imagenfondo());
        this.setExtendedState(ContenedorMDI.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuItem3 = new javax.swing.JMenuItem();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jmenuMaestros = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        Carreras = new javax.swing.JMenuItem();
        Cursos = new javax.swing.JMenuItem();
        Facultades = new javax.swing.JMenuItem();
        jmenuSecciones = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();

        jLabel1.setText("jLabel1");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 662, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 407, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 204));

        jMenu1.setText("Abrir");

        jMenuItem2.setText("Mantenimiento Alumnos");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jmenuMaestros.setText("Mantenimiento Maestros");
        jmenuMaestros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuMaestrosActionPerformed(evt);
            }
        });
        jMenu1.add(jmenuMaestros);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Catalogos");

        Carreras.setBackground(new java.awt.Color(255, 255, 153));
        Carreras.setText("Mantenimiento Carrera");
        Carreras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarrerasActionPerformed(evt);
            }
        });
        jMenu2.add(Carreras);

        Cursos.setBackground(new java.awt.Color(255, 255, 153));
        Cursos.setText("Mantenimiento Cursos");
        Cursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CursosActionPerformed(evt);
            }
        });
        jMenu2.add(Cursos);

        Facultades.setBackground(new java.awt.Color(255, 255, 153));
        Facultades.setText("Mantenimiento Facultades");
        Facultades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FacultadesActionPerformed(evt);
            }
        });
        jMenu2.add(Facultades);

        jmenuSecciones.setText("Mantenimiento Secciones");
        jmenuSecciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuSeccionesActionPerformed(evt);
            }
        });
        jMenu2.add(jmenuSecciones);

        jMenuBar1.add(jMenu2);

        jMenu3.setBackground(new java.awt.Color(255, 255, 153));
        jMenu3.setText("Procesos");

        jMenuItem4.setText("Asignacion Estudiantes");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Informes");
        jMenuBar1.add(jMenu4);

        jMenu5.setText("Herramientas");
        jMenuBar1.add(jMenu5);

        jMenu6.setText("Ayuda");
        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CursosActionPerformed
        // TODO add your handling code here:
        Cursos cu = new Cursos();
        jDesktopPane1.add(cu);
        cu.setVisible(true);
    }//GEN-LAST:event_CursosActionPerformed

    private void CarrerasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarrerasActionPerformed
        // TODO add your handling code here:
        Carreras cr = new Carreras();
        jDesktopPane1.add(cr);
        cr.setVisible(true);
    }//GEN-LAST:event_CarrerasActionPerformed

    private void FacultadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FacultadesActionPerformed
        // TODO add your handling code here:
        Facultades fr = new Facultades();
        jDesktopPane1.add(fr);
        fr.setVisible(true);
    }//GEN-LAST:event_FacultadesActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        MantenimientoAlumnos cs = new MantenimientoAlumnos();
        jDesktopPane1.add(cs);
        cs.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        ventana3 = new AsignacionEstudiantes();
        jDesktopPane1.add(ventana3);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jmenuSeccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuSeccionesActionPerformed
        Secciones secciones = new Secciones();
        jDesktopPane1.add(secciones);
        secciones.setVisible(true);
    }//GEN-LAST:event_jmenuSeccionesActionPerformed

    private void jmenuMaestrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuMaestrosActionPerformed
        MantenimientoMaestros maestros = new MantenimientoMaestros();
        jDesktopPane1.add(maestros);
        maestros.setVisible(true);
    }//GEN-LAST:event_jmenuMaestrosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContenedorMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContenedorMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContenedorMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContenedorMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContenedorMDI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Carreras;
    private javax.swing.JMenuItem Cursos;
    private javax.swing.JMenuItem Facultades;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jmenuMaestros;
    private javax.swing.JMenuItem jmenuSecciones;
    // End of variables declaration//GEN-END:variables

 

}
