/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author MoisesA
 */
public class ManFacultades extends javax.swing.JInternalFrame {

    /**
     * Creates new form ManFacultades
     */
    public ManFacultades() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Txtcodigofacultad = new javax.swing.JTextField();
        Txtnombrefacultad = new javax.swing.JTextField();
        Txtestadofacultad = new javax.swing.JTextField();
        btAlta2 = new javax.swing.JButton();
        btBaja = new javax.swing.JButton();
        btCambio = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        Txtbusqueda = new javax.swing.JTextField();
        btBuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setVisible(true);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel8.setText("Código Facultad:");

        jLabel9.setText("Nombre Facultad:");

        jLabel10.setText("Estado Facultad:");

        btAlta2.setText("Alta");
        btAlta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlta2ActionPerformed(evt);
            }
        });

        btBaja.setText("Baja");
        btBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBajaActionPerformed(evt);
            }
        });

        btCambio.setText("Cambio");
        btCambio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCambioActionPerformed(evt);
            }
        });

        jLabel11.setText("Código Facultad:");

        btBuscar.setText("Buscar");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btAlta2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btCambio, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Txtcodigofacultad)
                                    .addComponent(Txtnombrefacultad, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                    .addComponent(Txtestadofacultad))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(Txtbusqueda))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(Txtcodigofacultad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(Txtnombrefacultad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(Txtestadofacultad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAlta2)
                    .addComponent(btBaja)
                    .addComponent(btCambio))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(Txtbusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btBuscar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("MANTENIMIENTO FACULTADES");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAlta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlta2ActionPerformed
 try{
             Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/facultades", "root", "");
            PreparedStatement pst = cn.prepareStatement("insert into facultad values(?,?,?)");
            
            pst.setString(1, "0");
            pst.setString(2, Txtnombrefacultad.getText().trim());
            pst.setString(3, Txtestadofacultad.getText().trim());
            pst.executeUpdate();
            
            Txtnombrefacultad.setText("");
            Txtestadofacultad.setText("");
            JOptionPane.showMessageDialog(null, "REGISTRO REALIZADO");
        }catch (HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(null, e.toString());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btAlta2ActionPerformed

    private void btCambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCambioActionPerformed
try {
            String ID = Txtbusqueda.getText().trim();
            
 

            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/facultades", "root", "");
            PreparedStatement pst = cn.prepareStatement("update facultad set nombre_facultad = ?, estado_facultad = ? where id_facultad = " + ID);
            
            pst.setString(1, txtNomFacu.getText().trim());
            pst.setString(2, txtEsFacu.getText().trim());
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "REGISTRO MODIFICADO");
            
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
   

        // TODO add your handling code here:
    }//GEN-LAST:event_btCambioActionPerformed

    private void btBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBajaActionPerformed
      try {


            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/facultades", "root", "");
            PreparedStatement pst = cn.prepareStatement("delete from facultad where id_facultad = ?");
            
            pst.setString(1, Txtbusqueda.getText().trim());
            pst.executeUpdate();
            txtNomFacu.setText("");
            txtEsFacu.setText("");
            Txtbusqueda.setText("");
            
            JOptionPane.showMessageDialog(null, "REGISTRO ELIMINADO");
            
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }       // TODO add your handling code here:
    }//GEN-LAST:event_btBajaActionPerformed

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
  try{
           

            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/facultades", "root", "");
            PreparedStatement pst = cn.prepareStatement("select * from facultad where id_facultad = ?");
            pst.setString(1, Txtbusqueda.getText().trim());
            
            ResultSet rs = pst.executeQuery();
            
            if(rs.next()){
                txtNomFacu.setText(rs.getString("nombre_facultad"));
                txtEsFacu.setText(rs.getString("estado_facultad"));
            } else {
                JOptionPane.showMessageDialog(null, "CURSO NO REGISTRADO");
            }
            
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e.toString());
        }
    

        // TODO add your handling code here:
    }//GEN-LAST:event_btBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Txtbusqueda;
    private javax.swing.JTextField Txtcodigofacultad;
    private javax.swing.JTextField Txtestadofacultad;
    private javax.swing.JTextField Txtnombrefacultad;
    private javax.swing.JButton btAlta;
    private javax.swing.JButton btAlta1;
    private javax.swing.JButton btAlta2;
    private javax.swing.JButton btBaja;
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btCambio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtCodFacu;
    private javax.swing.JTextField txtCodFacu1;
    private javax.swing.JTextField txtEsFacu;
    private javax.swing.JTextField txtEsFacu1;
    private javax.swing.JTextField txtNomFacu;
    private javax.swing.JTextField txtNomFacu1;
    // End of variables declaration//GEN-END:variables
}
